name: modal_gif_picker
description: This package was created to get gif from GIPHY api, the is used in stories_editor package
version: 0.0.3
homepage: https://github.com/venkylm10/modal_gif_picker

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/
